version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: nuts_postgres
    environment:
      POSTGRES_DB: nutsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 098148675
    ports:
      - "5432:5432"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: nuts_rabbitmq
    ports:
      - "5672:5672"     # AMQP port for app
      - "15672:15672"   # Web UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build: .
    container_name: nuts_app
    depends_on:
      - postgres
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/nutsdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 098148675
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"
